import { describe, expect, it, beforeAll } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { db } from '../server/db.js';
import { historyDb } from '../server/history.js';
import request from './request.js';
import { loadConfig } from '../server/config.js';
import { IDS, SEASON } from './fixture.js';

/**
 * Signings OOTP never wrote a story about.
 *
 * "Transactions page shows only two of four contract extension signings... My
 * guess is that application picks up established star players, skipping over
 * those, who are perceived to be of a lesser caliber. First two guys have 'news
 * involving the player' generated by the game, last two don't, but all four
 * show up on team's transaction log as they should."
 *
 * He had the cause exactly and only misplaced the blame. There is no filter
 * here and never was: OOTP writes a news story for some signings and not
 * others, and the news is the only account of a signing the export carries.
 * The in-game transaction log he can see is not in the CSV — seventy-two
 * tables, and the only dated events in any of them are trades, news and
 * injuries.
 *
 * So the rest are recovered by noticing a man's deal changed between one
 * import and the next. This app refuses that kind of inference for roster
 * moves, where a call-up and a sale look identical; a contract is not
 * ambiguous. What it cannot recover is the day, so it reports the window and
 * says which it is.
 */

const QUIET_MAN = 9800;
const NEWSWORTHY = 9801;
const UNCHANGED = 9802;
const SAVE = loadConfig().saveName ?? 'unknown';

const EARLIER = `${SEASON}-8-4`;
const LATER = `${SEASON}-8-11`;

beforeAll(() => {
  const player = db.prepare(
    `INSERT INTO players (player_id, first_name, last_name, age, position, role, bats, throws,
                          uniform_number, team_id, organization_id, retired, hidden,
                          draft_eligible, college)
     VALUES (?, ?, ?, 25, 4, 0, 1, 1, ?, ?, ?, 0, 0, 0, 0)`
  );
  player.run(QUIET_MAN, 'Jesus', 'Moore', 81, IDS.mlbTeam, IDS.mlbTeam);
  player.run(NEWSWORTHY, 'Johnny', 'Esparza', 82, IDS.mlbTeam, IDS.mlbTeam);
  player.run(UNCHANGED, 'Same', 'Deal', 83, IDS.mlbTeam, IDS.mlbTeam);

  const snap = historyDb.prepare(
    `INSERT OR REPLACE INTO contract_snapshots
       (save_name, game_date, player_id, name, team_id, org_id, years, total, salary0)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`
  );
  // Before: all three on a one-year deal
  for (const [id, name] of [[QUIET_MAN, 'Jesus Moore'], [NEWSWORTHY, 'Johnny Esparza'],
                            [UNCHANGED, 'Same Deal']] as Array<[number, string]>) {
    snap.run(SAVE, EARLIER, id, name, IDS.mlbTeam, IDS.mlbTeam, 1, 500_000, 500_000);
  }
  // After: two of them signed five-year extensions, one did not
  snap.run(SAVE, LATER, QUIET_MAN, 'Jesus Moore', IDS.mlbTeam, IDS.mlbTeam, 5, 1_200_000, 240_000);
  snap.run(SAVE, LATER, NEWSWORTHY, 'Johnny Esparza', IDS.mlbTeam, IDS.mlbTeam, 5, 2_395_000, 479_000);
  snap.run(SAVE, LATER, UNCHANGED, 'Same Deal', IDS.mlbTeam, IDS.mlbTeam, 1, 500_000, 500_000);

  // OOTP wrote a story about one of them and not the other, which is the report
  db.prepare(
    `INSERT INTO messages (message_id, subject, date, message_type, team_id_0, team_id_1,
                           player_id_0, league_id_0, recipient_id)
     VALUES (?, ?, ?, 2, ?, 0, ?, ?, 1)`
  ).run(950, '2B Johnny Esparza: Contract Signed', `${SEASON}-8-7`, IDS.mlbTeam, NEWSWORTHY, IDS.league);
});

interface Txn {
  kind: string; plain: string; players: number[]; yours: boolean;
  date: string | null; seenBetween?: { from: string | null; to: string | null };
}

const feed = async (): Promise<Txn[]> =>
  (await request(`/api/transactions/${IDS.mlbTeam}`)).transactions as Txn[];

describe('a signing OOTP wrote no story about', () => {
  it('is reported anyway', async () => {
    // The whole of the complaint: four extensions, two shown
    const him = (await feed()).find((t) => t.players.includes(QUIET_MAN));
    expect(him, 'the quiet extension is still missing').toBeDefined();
    expect(him!.plain).toMatch(/Jesus Moore/);
  });

  it('says it was a five-year deal, which is what changed', async () => {
    const him = (await feed()).find((t) => t.players.includes(QUIET_MAN))!;
    expect(him.plain).toMatch(/5 years/);
  });

  it('is marked as the reader\'s own', async () => {
    expect((await feed()).find((t) => t.players.includes(QUIET_MAN))!.yours).toBe(true);
  });

  it('reports the window it happened in rather than inventing a day', async () => {
    /*
     * A range is genuinely all this knows — it is the difference between two
     * exports, not an event with a timestamp. The rows around it earned their
     * dates and this one has not.
     */
    const him = (await feed()).find((t) => t.players.includes(QUIET_MAN))!;
    expect(him.kind, 'a derived deal was dressed up as a reported one').toBe('contract');
    expect(him.seenBetween?.from).toBe(`${SEASON}-08-04`);
    expect(him.seenBetween?.to).toBe(`${SEASON}-08-11`);
  });
});

describe('a signing OOTP did write about', () => {
  it('is not reported twice', async () => {
    /*
     * The news said it better and said it on the day. A second line for the
     * same deal would make the page worse, not more complete.
     */
    const both = (await feed()).filter((t) => t.plain.includes('Esparza'));
    expect(both).toHaveLength(1);
    expect(both[0].kind, 'the news account lost out to the derived one').toBe('signing');
  });
});

describe('a man whose deal did not change', () => {
  it('is not reported at all', async () => {
    expect((await feed()).some((t) => t.players.includes(UNCHANGED))).toBe(false);
  });
});

describe('a save with only one import behind it', () => {
  it('derives nothing rather than treating every contract as new', async () => {
    /*
     * With one snapshot there is nothing to compare against, and reporting the
     * whole roster as freshly signed would be worse than reporting none of it.
     */
    historyDb.prepare(`DELETE FROM contract_snapshots WHERE game_date = ?`).run(EARLIER);
    try {
      expect((await feed()).some((t) => t.kind === 'contract')).toBe(false);
    } finally {
      const snap = historyDb.prepare(
        `INSERT OR REPLACE INTO contract_snapshots
           (save_name, game_date, player_id, name, team_id, org_id, years, total, salary0)
         VALUES (?, ?, ?, ?, ?, ?, 1, 500000, 500000)`
      );
      for (const [id, name] of [[QUIET_MAN, 'Jesus Moore'], [NEWSWORTHY, 'Johnny Esparza'],
                                [UNCHANGED, 'Same Deal']] as Array<[number, string]>) {
        snap.run(SAVE, EARLIER, id, name, IDS.mlbTeam, IDS.mlbTeam);
      }
    }
  });
});

const read = (rel: string) => fs.readFileSync(path.join(process.cwd(), rel), 'utf8');

describe('the page', () => {
  it('says where each kind of date comes from', () => {
    /*
     * He spent a paragraph working out why two were missing. The page should
     * have told him: the news is incomplete by OOTP's choice, not by mine.
     */
    const src = read('src/pages/Transactions.tsx').replace(/\s+/g, ' ');
    expect(src).toMatch(/does not write a story for every one/);
    expect(src).toMatch(/only the window it happened in, not the day/);
  });
});
